language: go

# Require Travis to use a docker-enabled virtualization environment for the build
sudo: required
services:
  - docker

# Go versions to build with
go:
    - 1.6
    - 1.5

env:
    global:
        # Required for Go 1.5 build
        - GO15VENDOREXPERIMENT=1
    matrix:
        # Platforms to build for
        - PLATFORM=linux/amd64

script:
    # Need to set explicitly, as these are unset by 'gimme'
    - export GOOS=${PLATFORM%/*}
    - export GOARCH=${PLATFORM#*/}
    
    # Analyze, test and build the code, and then package the binary
    - make verify release APP_VER=$TRAVIS_TAG

deploy:
    
    # Upload files to GitHub as release attachments
    -   provider: releases
        api_key: $GITHUB_TOKEN
      
        # Keep artifacts produced during the build
        skip_cleanup: true
    
        # Upload anything under the release directory
        file_glob: true
        file: release/*

        # Trigger only when building a tagged commit, on the origin repo, and with Go 1.6
        on:
            tags: true
            repo: amalgam8/registry
            go: 1.6

    # Push images to Docker Hub
    -   provider: script
        script: ./scripts/push_dockerhub.sh
    
        # Keep artifacts produced during the build
        skip_cleanup: true
            
        # Trigger only when building a version-tagged commit, on Go 1.6
        on:
            tags: true
            repo: amalgam8/registry
            go: 1.6
            condition: $TRAVIS_TAG =~ v[0-9]+\.[0-9]+\.[0-9]+
