language: go

# Require Travis to use a docker-enabled virtualization environment for the build
sudo: required
services:
  - docker

# Go versions to build with
go:
    - 1.6

env:
    # Platforms to build for
    - PLATFORM=linux/amd64

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
    - sudo rm /usr/local/bin/docker-compose || exit 0
    - curl -L https://github.com/docker/compose/releases/download/1.5.1/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin
    - sudo pip install git+https://github.com/amalgam8/a8ctl@master

install:
    - go get github.com/amalgam8/controller
    - go get github.com/amalgam8/registry
    - go get github.com/amalgam8/sidecar

script:
    # Need to set explicitly, as these are unset by 'gimme'
    - export GOOS=${PLATFORM%/*}
    - export GOARCH=${PLATFORM#*/}
    - export A8_CONTROLLER_URL=http://localhost:31200
    - export A8_REGISTRY_URL=http://localhost:31300
    - bash build_and_run.sh

# Configure notifications
notifications:
     email:
         on_success: never
         on_failure: always
     slack:
         rooms:
             - secure: "e7h0UYdA4dGgktZWxBTzw7zSio0RfNDSPOdgqszliYm8GaKTReTeiXpmwqY9X0Xk/X/FEdjRNZNIt1ZV7E323iHejJEx+1ocKvyJZrd3SFGaslpzIcWnj6nEod8v1gFidq1mvbuaiWil2QtmCzAo4rWpfjpthgJQZRiFCKvtCJOZTl326VOLGObWH2TiVFnwdRTZ598HtyL9TIv1DkTmKaQQR+h5+6AEsd+/f1MvQKXqbfrW4Jpu87N3pXU6aOm/37xn3RRMEvzDrO0VhBr1tmvo6KtFPp8z9jl4rA6mxM2URsSNTGgO7e/hMOMKwTBItaUGwFGTEwNvcYvT52FcMASt2uYFK0EpU8a4cbHIOhBR/yob7IebsVfR2dgXbMwrLsHf5iX9joeGTWmI5bT+E+XuI4N6yEXH8Cp9EWO++4X0P1GQ+ONY5NDrARNXCD+TLafAAWIILeBWu58gR3zdGi70FoqPPa//carsBUtk9/1wyTgpkammloTz316YvKWkop8fokT0oA7Pp54EKM6ECEFqgxwpTH/IKdycQGRHEGfYx21TjcgWezWJrGIRkggS/MPdsMmwN57tjP8y+hHq7zxsHyOUdfYYLoPLjEof/Oy+PnGk5Fcqm3+jgQ7KwetfmAfcpi6fjIgfvIekAcezK5l0ddGAwEJr7/+ZBEQQ2Pw="
         on_success: always
         on_failure: always
         on_pull_requests: true
